os: Visual Studio 2017

clone_depth: 100

cache:
    - C:\.hunter -> .appveyor.yml

environment:
    global:
        BOOST_ROOT: "C:/Libraries/boost_1_69_0"
        BOOST_LIBRARYDIR: "C:/Libraries/boost_1_69_0/lib64-msvc-14.1"
        Qt5_DIR: "C:/Qt/5.12/msvc2017_64/lib/cmake/Qt5"
    matrix:
        - Purpose: "WindowsDebugBuild"
          QWC_GENERATOR_NAME: "Visual Studio 15 2017 Win64"
          QWC_BUILD_TYPE: "Debug"
          QWC_TOOLCHAIN_FILE_NAME: "cmake/polly/vs-15-2017-win64.cmake"
          QWC_TESTS_REGEXP: "NONE"
        - Purpose: "WindowsReleaseBuild"
          QWC_GENERATOR_NAME: "Visual Studio 15 2017 Win64"
          QWC_BUILD_TYPE: "Release"
          QWC_TOOLCHAIN_FILE_NAME: "cmake/polly/vs-15-2017-win64.cmake"

install:
    - git submodule update --init --recursive

build_script:
    - md build
    - cd build
    - >
        cmake -G "%QWC_GENERATOR_NAME%"
        -DCMAKE_BUILD_TYPE=%QWC_BUILD_TYPE%
        -DCMAKE_TOOLCHAIN_FILE=%QWC_TOOLCHAIN_FILE_NAME%
        -DBUILD_ALL:BOOL=TRUE
        ..
    - cmake --build . --config %QWC_BUILD_TYPE%
    - cpack -C %QWC_BUILD_TYPE%

deploy:
    description: "Qwertycoin Zero release"
    provider: GitHub
    auth_token:
        secure: "tEcSlJaNMJjMRzn7ZBH7dfNV41/vem6wrQt+UDl2VTcTHrvsva4OBquvAkKVhsegOJ4ByGtPp16usE8fHnKQuzeFVpZ+FVRVyzw7QMdg7DU9fYXAiAuZFgtrRL85sZBqug26Xk/7GiMJ9hoHO+pQRX17q8ZQEaesVpjfD2BOSdGhVh7iQJf8JtvQv5CWYI6GWJSZhGJHuSfE5SpGgTUPAoK70APYeKZKvcWAgd0UJobvBKGIJFKMv5FrN/uf7sE/V3Rf6NHPQDiDHKWYKmJuBz/IZwM9wyCF7LxpyaywxS1YMe7roDA84YR+vHByXM6W4mnFGR03PpiHIRyef5k6SNBOpgcxPVwtuSugqgOF1tMSYuD+Bk2NWGORpAHjmIWbfZLvt6LSJhFY7NG9nsLghLDR8NTlYYDDY8EBjopaKh4KsExvPY3jt1Bfnt4ui1ZQl+BcYUuy98MGQ6/ck4/OJapWn60jnpKtojVz6BV08asG3I8YkatHDAJ83aTKvkWFer61ckz5QZUzwzFOf2GyUnURzjNvJNl+LJKxcFTyHLIObxa9u1ZtOXLH+w3p73dkKEXnQL7gMEjxUvugXP2i2+3CmOZ4PFYckcjespOuFpIwu2jtJwe3nz25ACk/+hX0k6SLO+nqCj9Oe3nnJasibB8eWVJqEy2ICxhhiFMokLU="
    artifact: /build\/dist\/qwertycoin-zero-*/
    draft: true
    prerelease: false
    on:
        APPVEYOR_REPO_TAG: true
        QWC_BUILD_TYPE: "Release"
