language: cpp

matrix:
    include:
        - name: "Linux, Debug"
          os: linux
          dist: xenial
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Debug"
              - CMAKE_TOOLCHAIN_FILE_NAME=gcc-cxx14-c11.cmake
              - Qt5_DIR="/usr/lib/x86_64-linux-gnu/cmake/Qt5"
        - name: "Linux, Release"
          os: linux
          dist: xenial
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=gcc-cxx14-c11.cmake
              - Qt5_DIR="/usr/lib/x86_64-linux-gnu/cmake/Qt5"
        - name: "macOS, Debug"
          os: osx
          osx_image: xcode10.2
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Debug"
              - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx14.cmake
              - Qt5_DIR="/usr/local/opt/qt/lib/cmake/Qt5"
        - name: "macOS, Release"
          os: osx
          osx_image: xcode10.2
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx14.cmake
              - Qt5_DIR="/usr/local/opt/qt/lib/cmake/Qt5"

addons:
    apt: # Linux
        packages:
            - build-essential
            - cmake
            - git
            - qtbase5-dev
            - unzip
            - wget
            - rpm
        sources:
            - ubuntu-toolchain-r-test
    homebrew: # macOS
        packages:
            - cmake
            - git
            - qt5

cache:
    directories:
        - $HOME/.hunter

script:
    - mkdir ./build && cd ./build
    - >
        cmake -G "$CMAKE_GENERATOR_NAME"
        -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
        -DCMAKE_TOOLCHAIN_FILE=cmake/polly/$CMAKE_TOOLCHAIN_FILE_NAME
        -DBUILD_ALL:BOOL=TRUE
        ..
    - cmake --build . --config $CMAKE_BUILD_TYPE -- -j 2
    - cpack -C $CMAKE_BUILD_TYPE
